/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StartRouteImport } from './routes/start'
import { Route as ShuffleRouteImport } from './routes/shuffle'
import { Route as ReframeRouteImport } from './routes/reframe'
import { Route as ReflectionRouteImport } from './routes/reflection'
import { Route as ObserveRouteImport } from './routes/observe'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CardsDebugRouteImport } from './routes/cards-debug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryReadingIdRouteImport } from './routes/history.$readingId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuffleRoute = ShuffleRouteImport.update({
  id: '/shuffle',
  path: '/shuffle',
  getParentRoute: () => rootRouteImport,
} as any)
const ReframeRoute = ReframeRouteImport.update({
  id: '/reframe',
  path: '/reframe',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionRoute = ReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => rootRouteImport,
} as any)
const ObserveRoute = ObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsDebugRoute = CardsDebugRouteImport.update({
  id: '/cards-debug',
  path: '/cards-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryReadingIdRoute = HistoryReadingIdRouteImport.update({
  id: '/$readingId',
  path: '/$readingId',
  getParentRoute: () => HistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards-debug': typeof CardsDebugRoute
  '/community': typeof CommunityRoute
  '/draw': typeof DrawRoute
  '/history': typeof HistoryRouteWithChildren
  '/observe': typeof ObserveRoute
  '/reflection': typeof ReflectionRoute
  '/reframe': typeof ReframeRoute
  '/shuffle': typeof ShuffleRoute
  '/start': typeof StartRoute
  '/welcome': typeof WelcomeRoute
  '/history/$readingId': typeof HistoryReadingIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards-debug': typeof CardsDebugRoute
  '/community': typeof CommunityRoute
  '/draw': typeof DrawRoute
  '/observe': typeof ObserveRoute
  '/reflection': typeof ReflectionRoute
  '/reframe': typeof ReframeRoute
  '/shuffle': typeof ShuffleRoute
  '/start': typeof StartRoute
  '/welcome': typeof WelcomeRoute
  '/history/$readingId': typeof HistoryReadingIdRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards-debug': typeof CardsDebugRoute
  '/community': typeof CommunityRoute
  '/draw': typeof DrawRoute
  '/history': typeof HistoryRouteWithChildren
  '/observe': typeof ObserveRoute
  '/reflection': typeof ReflectionRoute
  '/reframe': typeof ReframeRoute
  '/shuffle': typeof ShuffleRoute
  '/start': typeof StartRoute
  '/welcome': typeof WelcomeRoute
  '/history/$readingId': typeof HistoryReadingIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards-debug'
    | '/community'
    | '/draw'
    | '/history'
    | '/observe'
    | '/reflection'
    | '/reframe'
    | '/shuffle'
    | '/start'
    | '/welcome'
    | '/history/$readingId'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards-debug'
    | '/community'
    | '/draw'
    | '/observe'
    | '/reflection'
    | '/reframe'
    | '/shuffle'
    | '/start'
    | '/welcome'
    | '/history/$readingId'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/cards-debug'
    | '/community'
    | '/draw'
    | '/history'
    | '/observe'
    | '/reflection'
    | '/reframe'
    | '/shuffle'
    | '/start'
    | '/welcome'
    | '/history/$readingId'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsDebugRoute: typeof CardsDebugRoute
  CommunityRoute: typeof CommunityRoute
  DrawRoute: typeof DrawRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  ObserveRoute: typeof ObserveRoute
  ReflectionRoute: typeof ReflectionRoute
  ReframeRoute: typeof ReframeRoute
  ShuffleRoute: typeof ShuffleRoute
  StartRoute: typeof StartRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuffle': {
      id: '/shuffle'
      path: '/shuffle'
      fullPath: '/shuffle'
      preLoaderRoute: typeof ShuffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reframe': {
      id: '/reframe'
      path: '/reframe'
      fullPath: '/reframe'
      preLoaderRoute: typeof ReframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflection': {
      id: '/reflection'
      path: '/reflection'
      fullPath: '/reflection'
      preLoaderRoute: typeof ReflectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observe': {
      id: '/observe'
      path: '/observe'
      fullPath: '/observe'
      preLoaderRoute: typeof ObserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards-debug': {
      id: '/cards-debug'
      path: '/cards-debug'
      fullPath: '/cards-debug'
      preLoaderRoute: typeof CardsDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$readingId': {
      id: '/history/$readingId'
      path: '/$readingId'
      fullPath: '/history/$readingId'
      preLoaderRoute: typeof HistoryReadingIdRouteImport
      parentRoute: typeof HistoryRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryReadingIdRoute: typeof HistoryReadingIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryReadingIdRoute: HistoryReadingIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsDebugRoute: CardsDebugRoute,
  CommunityRoute: CommunityRoute,
  DrawRoute: DrawRoute,
  HistoryRoute: HistoryRouteWithChildren,
  ObserveRoute: ObserveRoute,
  ReflectionRoute: ReflectionRoute,
  ReframeRoute: ReframeRoute,
  ShuffleRoute: ShuffleRoute,
  StartRoute: StartRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
